version: '3'
services:
  next-app:
    container_name: next-app
    build: .
    ports:
      - "3000:3000"
    tty: true
    stdin_open: true
    volumes:
      - ./:/app/
      - /app/node_modules
      - /app/.next
